[package]
name = "gnome-egpu"
version = "0.1.0"
authors = ["dan.greco@live.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gudev = "0.9.0"
glib = { version = "^0.10.0" }
dialoguer = "0.7.1"
sudo = "0.6.0"
